<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * @var list<string>
     */
    private array $permissions = [
        'dashboard.view',
        'clients.view',
        'clients.create',
        'clients.update',
        'clients.delete',
        'contacts.view',
        'contacts.create',
        'contacts.update',
        'contacts.delete',
        'opportunities.view',
        'opportunities.create',
        'opportunities.update',
        'opportunities.delete',
        'contracts.view',
        'contracts.create',
        'contracts.update',
        'contracts.delete',
        'contracts.approve',
        'deployments.view',
        'deployments.create',
        'deployments.update',
        'deployments.delete',
        'deployments.provision',
        'deployments.release',
        'deployments.rollback',
        'infrastructure.view',
        'infrastructure.create',
        'infrastructure.update',
        'infrastructure.delete',
        'monitoring.view',
        'monitoring.create',
        'monitoring.update',
        'monitoring.delete',
        'monitoring.resolve',
        'support_agreements.view',
        'support_agreements.create',
        'support_agreements.update',
        'support_agreements.delete',
        'support_tickets.view',
        'support_tickets.create',
        'support_tickets.update',
        'support_tickets.assign',
        'support_tickets.resolve',
        'support_tickets.close',
        'support_tickets.comment',
        'billing.view',
        'billing.create',
        'billing.update',
        'billing.delete',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'invoices.delete',
        'invoices.send',
        'invoices.mark_paid',
        'payments.view',
        'payments.create',
        'payments.update',
        'payments.delete',
        'profitability.view',
        'profitability.create',
        'profitability.update',
        'profitability.delete',
        'incidents.view',
        'incidents.create',
        'incidents.update',
        'incidents.resolve',
        'incidents.close',
        'releases.view',
        'releases.create',
        'releases.update',
        'releases.approve',
        'releases.deploy',
        'releases.rollback',
        'reports.view',
        'reports.export',
        'products.view',
        'products.create',
        'products.update',
        'products.delete',
        'packages.view',
        'packages.create',
        'packages.update',
        'packages.delete',
        'catalogue_features.view',
        'catalogue_features.create',
        'catalogue_features.update',
        'catalogue_features.delete',
        'support_tiers.view',
        'support_tiers.create',
        'support_tiers.update',
        'support_tiers.delete',
        'lookups.view',
        'lookups.create',
        'lookups.update',
        'lookups.delete',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'roles.view',
        'roles.create',
        'roles.update',
        'roles.delete',
        'permissions.view',
        'permissions.assign',
        'profile.view',
        'profile.update',
        'profile.manage_avatar',
        'media.view',
        'media.upload',
        'media.delete',
        'settings.view',
        'settings.update',
        'activity.view',
        'horizon.view',
    ];

    /**
     * @var array<string, list<string>>
     */
    private array $rolePermissions = [
        'administrator' => [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'permissions.view',
            'permissions.assign',
            'products.view',
            'products.create',
            'products.update',
            'products.delete',
            'packages.view',
            'packages.create',
            'packages.update',
            'packages.delete',
            'catalogue_features.view',
            'catalogue_features.create',
            'catalogue_features.update',
            'catalogue_features.delete',
            'support_tiers.view',
            'support_tiers.create',
            'support_tiers.update',
            'support_tiers.delete',
            'settings.view',
            'settings.update',
            'activity.view',
            'horizon.view',
            'profile.view',
            'profile.update',
            'profile.manage_avatar',
            'media.view',
            'media.upload',
            'media.delete',
        ],
        'executive' => [
            'dashboard.view',
            'clients.view',
            'contacts.view',
            'opportunities.view',
            'contracts.view',
            'deployments.view',
            'infrastructure.view',
            'monitoring.view',
            'support_agreements.view',
            'support_tickets.view',
            'billing.view',
            'invoices.view',
            'payments.view',
            'profitability.view',
            'incidents.view',
            'releases.view',
            'reports.view',
            'reports.export',
            'profile.view',
            'profile.update',
        ],
        'operations' => [
            'dashboard.view',
            'clients.view',
            'contacts.view',
            'deployments.view',
            'deployments.create',
            'deployments.update',
            'deployments.provision',
            'infrastructure.view',
            'infrastructure.create',
            'infrastructure.update',
            'monitoring.view',
            'monitoring.create',
            'monitoring.update',
            'monitoring.resolve',
            'incidents.view',
            'incidents.create',
            'incidents.update',
            'incidents.resolve',
            'incidents.close',
            'support_tickets.view',
            'support_tickets.update',
            'support_tickets.assign',
            'support_tickets.resolve',
            'support_tickets.comment',
            'reports.view',
            'profile.view',
            'profile.update',
        ],
        'finance' => [
            'dashboard.view',
            'clients.view',
            'contracts.view',
            'billing.view',
            'billing.create',
            'billing.update',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'invoices.send',
            'invoices.mark_paid',
            'payments.view',
            'payments.create',
            'payments.update',
            'profitability.view',
            'profitability.create',
            'profitability.update',
            'reports.view',
            'reports.export',
            'profile.view',
            'profile.update',
        ],
        'sales' => [
            'dashboard.view',
            'clients.view',
            'clients.create',
            'clients.update',
            'contacts.view',
            'contacts.create',
            'contacts.update',
            'opportunities.view',
            'opportunities.create',
            'opportunities.update',
            'contracts.view',
            'contracts.create',
            'contracts.update',
            'reports.view',
            'profile.view',
            'profile.update',
        ],
        'support' => [
            'dashboard.view',
            'clients.view',
            'contacts.view',
            'support_agreements.view',
            'support_tickets.view',
            'support_tickets.create',
            'support_tickets.update',
            'support_tickets.assign',
            'support_tickets.resolve',
            'support_tickets.close',
            'support_tickets.comment',
            'monitoring.view',
            'incidents.view',
            'incidents.create',
            'reports.view',
            'profile.view',
            'profile.update',
        ],
        'technical' => [
            'dashboard.view',
            'clients.view',
            'contacts.view',
            'deployments.view',
            'deployments.create',
            'deployments.update',
            'deployments.release',
            'deployments.rollback',
            'infrastructure.view',
            'infrastructure.create',
            'infrastructure.update',
            'monitoring.view',
            'monitoring.create',
            'monitoring.update',
            'monitoring.resolve',
            'incidents.view',
            'incidents.create',
            'incidents.update',
            'incidents.resolve',
            'releases.view',
            'releases.create',
            'releases.update',
            'releases.deploy',
            'releases.rollback',
            'support_tickets.view',
            'support_tickets.update',
            'support_tickets.resolve',
            'support_tickets.comment',
            'reports.view',
            'profile.view',
            'profile.update',
        ],
    ];

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        foreach ($this->permissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }

        foreach ($this->rolePermissions as $roleName => $permissions) {
            $role = Role::firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            $role->syncPermissions($roleName === 'administrator' ? $this->permissions : $permissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
