/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/catalogue-features': RouteRecordInfo<
      '/admin/catalogue-features',
      '/admin/catalogue-features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/packages': RouteRecordInfo<
      '/admin/packages',
      '/admin/packages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/products': RouteRecordInfo<
      '/admin/products',
      '/admin/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reference-data': RouteRecordInfo<
      '/admin/reference-data',
      '/admin/reference-data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/support-tiers': RouteRecordInfo<
      '/admin/support-tiers',
      '/admin/support-tiers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/profile': RouteRecordInfo<
      '/auth/profile',
      '/auth/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verify': RouteRecordInfo<
      '/auth/verify',
      '/auth/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/': RouteRecordInfo<
      '/clients/',
      '/clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/[client]': RouteRecordInfo<
      '/clients/[client]',
      '/clients/:client',
      { client: ParamValue<true> },
      { client: ParamValue<false> },
      | never
    >,
    '/commercial/billing': RouteRecordInfo<
      '/commercial/billing',
      '/commercial/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commercial/contracts/': RouteRecordInfo<
      '/commercial/contracts/',
      '/commercial/contracts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commercial/contracts/[contract]': RouteRecordInfo<
      '/commercial/contracts/[contract]',
      '/commercial/contracts/:contract',
      { contract: ParamValue<true> },
      { contract: ParamValue<false> },
      | never
    >,
    '/commercial/invoices/': RouteRecordInfo<
      '/commercial/invoices/',
      '/commercial/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commercial/invoices/[invoice]': RouteRecordInfo<
      '/commercial/invoices/[invoice]',
      '/commercial/invoices/:invoice',
      { invoice: ParamValue<true> },
      { invoice: ParamValue<false> },
      | never
    >,
    '/commercial/opportunities': RouteRecordInfo<
      '/commercial/opportunities',
      '/commercial/opportunities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commercial/profitability': RouteRecordInfo<
      '/commercial/profitability',
      '/commercial/profitability',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/automation': RouteRecordInfo<
      '/operations/automation',
      '/operations/automation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/change-requests': RouteRecordInfo<
      '/operations/change-requests',
      '/operations/change-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/dashboard': RouteRecordInfo<
      '/operations/dashboard',
      '/operations/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/deployments/': RouteRecordInfo<
      '/operations/deployments/',
      '/operations/deployments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/deployments/[deployment]': RouteRecordInfo<
      '/operations/deployments/[deployment]',
      '/operations/deployments/:deployment',
      { deployment: ParamValue<true> },
      { deployment: ParamValue<false> },
      | never
    >,
    '/operations/incidents': RouteRecordInfo<
      '/operations/incidents',
      '/operations/incidents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/infrastructure': RouteRecordInfo<
      '/operations/infrastructure',
      '/operations/infrastructure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/monitoring': RouteRecordInfo<
      '/operations/monitoring',
      '/operations/monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/provisioning': RouteRecordInfo<
      '/operations/provisioning',
      '/operations/provisioning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/releases/': RouteRecordInfo<
      '/operations/releases/',
      '/operations/releases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/releases/[release]': RouteRecordInfo<
      '/operations/releases/[release]',
      '/operations/releases/:release',
      { release: ParamValue<true> },
      { release: ParamValue<false> },
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/agreements': RouteRecordInfo<
      '/support/agreements',
      '/support/agreements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/sla-overview': RouteRecordInfo<
      '/support/sla-overview',
      '/support/sla-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/tickets/': RouteRecordInfo<
      '/support/tickets/',
      '/support/tickets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/tickets/[ticket]': RouteRecordInfo<
      '/support/tickets/[ticket]',
      '/support/tickets/:ticket',
      { ticket: ParamValue<true> },
      { ticket: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/js/app/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'resources/js/app/pages/admin/catalogue-features.vue': {
      routes:
        | '/admin/catalogue-features'
      views:
        | never
    }
    'resources/js/app/pages/admin/packages.vue': {
      routes:
        | '/admin/packages'
      views:
        | never
    }
    'resources/js/app/pages/admin/products.vue': {
      routes:
        | '/admin/products'
      views:
        | never
    }
    'resources/js/app/pages/admin/reference-data.vue': {
      routes:
        | '/admin/reference-data'
      views:
        | never
    }
    'resources/js/app/pages/admin/support-tiers.vue': {
      routes:
        | '/admin/support-tiers'
      views:
        | never
    }
    'resources/js/app/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'resources/js/app/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'resources/js/app/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'resources/js/app/pages/auth/profile.vue': {
      routes:
        | '/auth/profile'
      views:
        | never
    }
    'resources/js/app/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
    }
    'resources/js/app/pages/auth/verify.vue': {
      routes:
        | '/auth/verify'
      views:
        | never
    }
    'resources/js/app/pages/clients/index.vue': {
      routes:
        | '/clients/'
      views:
        | never
    }
    'resources/js/app/pages/clients/[client].vue': {
      routes:
        | '/clients/[client]'
      views:
        | never
    }
    'resources/js/app/pages/commercial/billing.vue': {
      routes:
        | '/commercial/billing'
      views:
        | never
    }
    'resources/js/app/pages/commercial/contracts/index.vue': {
      routes:
        | '/commercial/contracts/'
      views:
        | never
    }
    'resources/js/app/pages/commercial/contracts/[contract].vue': {
      routes:
        | '/commercial/contracts/[contract]'
      views:
        | never
    }
    'resources/js/app/pages/commercial/invoices/index.vue': {
      routes:
        | '/commercial/invoices/'
      views:
        | never
    }
    'resources/js/app/pages/commercial/invoices/[invoice].vue': {
      routes:
        | '/commercial/invoices/[invoice]'
      views:
        | never
    }
    'resources/js/app/pages/commercial/opportunities.vue': {
      routes:
        | '/commercial/opportunities'
      views:
        | never
    }
    'resources/js/app/pages/commercial/profitability.vue': {
      routes:
        | '/commercial/profitability'
      views:
        | never
    }
    'resources/js/app/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'resources/js/app/pages/operations/automation.vue': {
      routes:
        | '/operations/automation'
      views:
        | never
    }
    'resources/js/app/pages/operations/change-requests.vue': {
      routes:
        | '/operations/change-requests'
      views:
        | never
    }
    'resources/js/app/pages/operations/dashboard.vue': {
      routes:
        | '/operations/dashboard'
      views:
        | never
    }
    'resources/js/app/pages/operations/deployments/index.vue': {
      routes:
        | '/operations/deployments/'
      views:
        | never
    }
    'resources/js/app/pages/operations/deployments/[deployment].vue': {
      routes:
        | '/operations/deployments/[deployment]'
      views:
        | never
    }
    'resources/js/app/pages/operations/incidents.vue': {
      routes:
        | '/operations/incidents'
      views:
        | never
    }
    'resources/js/app/pages/operations/infrastructure.vue': {
      routes:
        | '/operations/infrastructure'
      views:
        | never
    }
    'resources/js/app/pages/operations/monitoring.vue': {
      routes:
        | '/operations/monitoring'
      views:
        | never
    }
    'resources/js/app/pages/operations/provisioning.vue': {
      routes:
        | '/operations/provisioning'
      views:
        | never
    }
    'resources/js/app/pages/operations/releases/index.vue': {
      routes:
        | '/operations/releases/'
      views:
        | never
    }
    'resources/js/app/pages/operations/releases/[release].vue': {
      routes:
        | '/operations/releases/[release]'
      views:
        | never
    }
    'resources/js/app/pages/reports.vue': {
      routes:
        | '/reports'
      views:
        | never
    }
    'resources/js/app/pages/support/agreements.vue': {
      routes:
        | '/support/agreements'
      views:
        | never
    }
    'resources/js/app/pages/support/sla-overview.vue': {
      routes:
        | '/support/sla-overview'
      views:
        | never
    }
    'resources/js/app/pages/support/tickets/index.vue': {
      routes:
        | '/support/tickets/'
      views:
        | never
    }
    'resources/js/app/pages/support/tickets/[ticket].vue': {
      routes:
        | '/support/tickets/[ticket]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
